# -*- coding: utf-8 -*-
"""EISKO_matching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkoZPt6v23gtMhvbE0qBFm6lrcNbxY-C
"""

## ORB FEATURE MATCHING ###

## ORB feature matching, checks two images and returns score between 0 and 1
def orb_similarity(img1, img2):

    # Initialize ORB detector
    orb = cv.ORB_create(500)

    # Detect and compute keypoints/descriptors
    kp1, des1 = orb.detectAndCompute(img1, None)
    kp2, des2 = orb.detectAndCompute(img2, None)

    # If no descriptors found, return 0 similarity
    if des1 is None or des2 is None:
        return 0.0

    # Hamming-distance BFMatcher
    bf = cv.BFMatcher(cv.NORM_HAMMING, crossCheck=True)

    matches = bf.match(des1, des2)

    if len(matches) == 0:
        return 0.0

    # Convert distances to similarity score
    distances = [m.distance for m in matches]

    # Normalize: 0=best, 256=worst
    avg_distance = np.mean(distances)
    similarity = 1 - (avg_distance / 256)

    # Clamp to [0,1]
    return max(0, min(1, similarity))

## END OF ORB ##

## Getting similarity scores with template matching
## Input: img: the image to check. templates, array with each template
def orb_templatematching(img, templates):
  sim_scores = []
  for templ in templates:
    score = orb_similarity(img, templ)
    sim_scores.append(score)
  return sim_scores

## Processing template matching scores.
## Input: template matching scores in array
matches = []
match = False
def process_scores(scores):
  for i in range(len(scores)):
    score = scores[i]
    if score > 0.9:
      matches.append([compo_names[i],score])
      match = True
  return matches, match